name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # — contoh lint, boleh di-skip jika belum pakai flake8/pytest —
      - name: (Optional) Lint
        run: |
          pip install flake8
          flake8 .

      # Trigger deploy ke Sevalla via hook
      - name: Trigger Sevalla Deploy
        run: curl -X POST ${{ secrets.SEVALLA_DEPLOY_HOOK }}
